### write
POST https://localhost:4000/write
Content-Type: application/json

{
  "key": "hello",
  "value": "there"
}

### read
GET https://localhost:4000/read/hello

### delete
DELETE https://localhost:4000/delete
Content-Type: application/json

{
  "key": "hello"
}

### events
GET https://localhost:4000/events