services:
  redis:
    build:
      context: ./redis
    ports:
      - "6379"
    networks:
      - node-network

  node:
    build:
      context: ./node
    deploy:
      replicas: 5
      endpoint_mode: dnsrr
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080"
    networks:
        - node-network
    depends_on:
      - redis

  nginx:
    build:
      context: ./reverse-proxy
    ports:
      - "4000:443"
    depends_on:
      - node
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
